CREATE TABLE IF NOT EXISTS users (
                                     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
                                     login VARCHAR(255) NOT NULL,
                                     email VARCHAR(255) NOT NULL,
                                     birthday DATE NOT NULL,
                                     CONSTRAINT uq_users_login UNIQUE (login),
                                     CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS mpa (
                                   mpa_id INTEGER PRIMARY KEY,
                                   name VARCHAR(50) NOT NULL,
                                   description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS friendship_status (
                                                 status BOOLEAN PRIMARY KEY,
                                                 name VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genre (
                                     genre_id INTEGER PRIMARY KEY,
                                     genre_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
                                     film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(1000),
                                     release_date DATE NOT NULL,
                                     duration INTEGER NOT NULL CHECK (duration > 0),
                                     mpa_id INTEGER NOT NULL,
                                     CONSTRAINT fk_films_mpa
                                         FOREIGN KEY (mpa_id) REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
                                          user_id BIGINT NOT NULL,
                                          film_id BIGINT NOT NULL,
                                          PRIMARY KEY (user_id, film_id),
                                          CONSTRAINT fk_film_likes_user
                                              FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
                                          CONSTRAINT fk_film_likes_film
                                              FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friendship (
                                          user_id BIGINT NOT NULL,
                                          friend_id BIGINT NOT NULL,
                                          status BOOLEAN NOT NULL,
                                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          PRIMARY KEY (user_id, friend_id),
                                          CONSTRAINT fk_friendship_user
                                              FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
                                          CONSTRAINT fk_friendship_friend
                                              FOREIGN KEY (friend_id) REFERENCES users (user_id) ON DELETE CASCADE,
                                          CONSTRAINT fk_friendship_status
                                              FOREIGN KEY (status) REFERENCES friendship_status (status),
                                          CONSTRAINT chk_friendship_not_self
                                              CHECK (user_id <> friend_id)
);

CREATE TABLE IF NOT EXISTS genre_films (
                                           film_id BIGINT NOT NULL,
                                           genre_id INTEGER NOT NULL,
                                           PRIMARY KEY (film_id, genre_id),
                                           CONSTRAINT fk_genre_films_film
                                               FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE,
                                           CONSTRAINT fk_genre_films_genre
                                               FOREIGN KEY (genre_id) REFERENCES genre (genre_id)
);

CREATE INDEX IF NOT EXISTS idx_films_mpa_id
    ON films (mpa_id);

CREATE INDEX IF NOT EXISTS idx_film_likes_film_id
    ON film_likes (film_id);

CREATE INDEX IF NOT EXISTS idx_friendship_friend_id
    ON friendship (friend_id);

CREATE INDEX IF NOT EXISTS idx_friendship_status
    ON friendship (status);

CREATE INDEX IF NOT EXISTS idx_genre_films_genre_id
    ON genre_films (genre_id);